language: node_js
node_js: node
python:
- '2.7'
addons:
  firefox: latest
install:
  - npm install
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "pip install -r test/demo/pip_require.txt"
  - python test/demo/run.py &
