language: node_js
node_js: node
install:
  - npm install -g npm@4
  - npm install
addons:
  firefox: "54.0"
before_script: npm run build
before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
